### ISSUE TITLE
It does not change its image

### ISSUE THREAD

**Issue by cesarpe** [LeoNero/react-img-zoom#18]
Hello,
When I do this, it works
<Zoom
   img = {this.state.imgcur}
   zoomScale = {3}
   height = {450}
   width = {400}
   transitionTime = {0.5}
   />
but when I change the image with this.setState ({imgcur: newImage}), it does not refresh

**Comment by cesarpe** [comment]
I solved it by adding a value to the key
<Zoom key = {this.state.key}
   img = {this.state.imgcur}
   zoomScale = {3}
   height = {450}
   width = {400}
   transitionTime = {0.5}
   />
Change the index and the new image, to update the 2 values
this.setState ({imgcur: newImage, key: index}),

Thanks for the code

**Comment by LeoNero** [comment]
Hi @cesarpe ! Glad you were able to solve it.

Also, I will create another issue so that I can remember to see if there is another solution :)
